blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^categorie/(?P<slug>[\w-]+)/$', views.category, name='category'),
	url(r'^recherche/$', views.search, name='search'),
	url(r'^categorie/(?P<parent__slug>[\w-]+)/(?P<slug>[\w-]+)/$', views.category, name='subcategory'),
	url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='post'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^markdownx/', include('markdownx.urls')),
	url(r'^', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import m2m_changed, pre_save
from django.utils.text import slugify


class Category(models.Model):
	name = models.CharField(max_length=50)
	slug = models.CharField(max_length=100, blank=True)
	position = models.IntegerField(blank=True, editable=False)
	icon = models.CharField(max_length=50, blank=True)

	parent = models.ForeignKey('self', blank=True, null=True, related_name="children")

	class Meta:
		ordering = ('position',)
		verbose_name_plural = "Categories"
		verbose_name = "Categorie"

	def __str__(self):
		return self.name
		# return ("-- " if self.parent != None else "") + self.name

	def get_name(self):
		return ("-- " if self.parent != None else "") + self.name
	get_name.short_description = 'Name'

	def generate_slug(self, new_slug=None):
		qs = Category.objects.filter(slug=new_slug).order_by('-id')
		exists = qs.exists()
		if exists:
			new_slug = "%s-%s" % (new_slug, qs.first().id)
			return self.generate_slug(new_slug=new_slug)
		return new_slug

	def get_absolute_url(self):
		if self.parent is None:
			return reverse('blog:category', kwargs={'slug': self.slug})
		return reverse('blog:subcategory', kwargs={'slug': self.slug, 'parent__slug': self.parent.slug})

	@staticmethod
	def pre_save(sender, instance, *args, **kwargs):
		order = 1
		parents = Category.objects.filter(parent=None)
		for parent in parents:
			Category.objects.filter(pk=parent.pk).update(position=order)
			order += 1
			children = Category.objects.filter(parent=parent.id).order_by('name',)
			for child in children:
				Category.objects.filter(pk=child.pk).update(position=order)
				order += 1

		if not instance.slug:
			instance.slug = instance.generate_slug(new_slug=slugify(instance.name))

pre_save.connect(Category.pre_save, Category)


class Post(models.Model):
	title = models.CharField(max_length=255)
	content = models.TextField()
	slug = models.SlugField(max_length=100, blank=True)

	date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
	date_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
	date_published = models.DateField(auto_now_add=False, auto_now=False)

	categories = models.ManyToManyField(Category)
	# tags = models.ManyToMany(tag)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ('-date_published', '-date_created', '-date_modified')

	def generate_slug(self, new_slug=None):
		qs = Post.objects.filter(slug=new_slug).order_by('-id')
		exists = qs.exists()
		if exists:
			new_slug = "%s-%s" % (new_slug, qs.first().id)
			return self.generate_slug(new_slug=new_slug)
		return new_slug

	def get_absolute_url(self):
		return reverse('blog:post', kwargs={'slug': self.slug})


	@staticmethod
	def pre_save(sender, instance, *args, **kwargs):
		if not instance.slug:
			instance.slug = instance.generate_slug(new_slug=slugify(instance.title))

pre_save.connect(Post.pre_save, Post)

blog/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from .models import Category, Post

def home(request):
	queryset_list = Post.objects.all()

	paginator = Paginator(queryset_list, 25)

	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)

	context = {
		'objects': queryset,
	}

	return render(request, 'blog/posts.html', context)

def category(request, *args, **kwargs):

	instance = get_object_or_404(Category, *args, **kwargs)

	queryset_list = Post.objects.filter( Q(categories__id=instance.id) | Q(categories__parent__id=instance.id) ).distinct()

	paginator = Paginator(queryset_list, 25)

	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)


	header_title = instance.name
	header_icon = instance.icon
	if instance.parent:
		header_icon = instance.parent.icon
		header_title = "%s / %s" % (instance.parent.name, header_title)

	context = {
		'header_title': header_title,
		'header_icon': header_icon,
		'category': instance,
		'objects': queryset,
		'empty_content': 'Aucun article dans cette catégorie',
	}

	return render(request, 'blog/posts.html', context)


def search(request):

	query = request.GET.get("q")
	if query:
		queryset = Post.objects.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query)
		).distinct()

	context = {
		'header_title': 'Recherche pour %s' % (query),
		'header_icon': 'search',
		'objects': queryset,
		'empty_content': 'Aucun article trouvé avec cette recherche',
	}

	return render(request, 'blog/posts.html', context)


def post_detail(request, *args, **kwargs):

	instance = get_object_or_404(Post, *args, **kwargs)

	context = {
		'post': instance,
	}

	return render(request, 'blog/post.html', context)

templates/base.html
{% load staticfiles %}
{% load menu %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="description" content="{% block meta_description %}{% endblock meta_description %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
		<title>{% block meta_title %}birkoss.com{% endblock meta_title %}</title>

		<!-- Add to homescreen -->
		<link rel="manifest" href="manifest.json" />

		<!-- Fallback to homescreen for Chrome <39 on Android -->
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="application-name" content="Material Design Lite" />
		<link rel="icon" sizes="192x192" href="../assets/android-desktop.png" />

		<!-- Add to homescreen for Safari on iOS -->
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black" />
		<meta name="apple-mobile-web-app-title" content="Material Design Lite" />
		<link rel="apple-touch-icon" href="../assets/ios-desktop.png" />

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
		<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css" />

		<link rel="stylesheet" href="{% static "css/style.css" %}" />
	</head>
	<body>

		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
			<header class="mdl-layout__header">
				<div class="mdl-layout__header-row">
					<div class="mdl-layout-title mdl-cell--hide-desktop"><a href="{% url 'blog:home' %}">birkoss.com</a></div>
					<div class="mdl-layout-spacer"></div>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
						<label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
							<i class="material-icons">search</i>
						</label>
						<div class="mdl-textfield__expandable-holder">
							<form method="get" action="{% url 'blog:search' %}">
								<input class="mdl-textfield__input" type="text" name="q" value="{{ request.GET.q }}" id="fixed-header-drawer-exp">
							</form>
						</div>
					</div>
				</div>
			</header>
			<div class="mdl-layout__drawer">
				<span class="mdl-layout-title"><a href="{% url 'blog:home' %}">birkoss.com</a></span>
				<nav class="mdl-navigation">
					{% show_menu_categories %}
				</nav>

				<nav class="socials">
					<a href="https://twitter.com/birkoss"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-stack-1x fa-inverse fa-twitter"></i></span></a>
					<a href="https://birkoss.com/birkoss.asc"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-stack-1x fa-inverse fa-key"></i></span></a>
					<a href="https://github.com/birkoss"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-stack-1x fa-inverse fa-github"></i></span></a>
				</nav>

			</div>
			<main class="mdl-layout__content">
				<div class="page-content">
					{% block content %}
						Content...
					{% endblock content %}
				</div>
			</main>
		</div>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		  ga('create', 'UA-34357238-3', 'auto');
		  ga('send', 'pageview');
		</script>

		<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
	</body>
</html>

templates/blog/home.html
sway

templates/blog/post.html
{% extends "base.html" %}
{% load md %}

{% block content %}
<div class="mdl-grid container-title">
	<div class="mdl-cell mdl-cell--12-col">
		<h1>
			<span>
				<i class="fa fa-file"></i>
				{{ post.title }}
			</span>
		</h1>
	</div>
</div>
<div class="mdl-grid container-content">

	<div class="mdl-cell mdl-cell--8-col mdl-cell--2-offset-desktop">
		<div class="post-card mdl-card mdl-shadow--2dp">
			<div class="mdl-card__supporting-text">{{ post.content | md | safe }}</div>
			<div class="mdl-card__actions mdl-card--border">
				{% for category in post.categories.all %}
					<a href="{{ category.get_absolute_url }}" class="mdl-button mdl-js-button mdl-js-ripple-effect">{{ category.name }}</a>
				{% endfor %}
			</div>
		</div>
	</div>

</div>
{% endblock %}

templates/blog/posts.html
{% extends "base.html" %}
{% load md %}

{% block content %}
	{% if header_title %}
		<div class="mdl-grid container-title">
			<div class="mdl-cell mdl-cell--12-col">
				<h1>
					<span>
						{% if header_icon %}<i class="fa fa-{{ header_icon }}"></i> {% endif %}
						{{ header_title }}
					</span>
				</h1>
			</div>
		</div>
	{% endif %}
<div class="mdl-grid container-content">
	{% if objects %}
		{% for obj in objects %}
			<div class="mdl-cell mdl-cell--8-col mdl-cell--2-offset-desktop">
				<div class="post-card mdl-card mdl-shadow--2dp">
					<div class="mdl-card__title">
						<h2 class="mdl-card__title-text">{{ obj.title }}</h2>
					</div>
					<div class="mdl-card__supporting-text">{{ obj.content | md | safe | truncatechars_html:255 }}</div>
					<div class="mdl-card__actions mdl-card--border">
						<a href="{{ obj.get_absolute_url }}" class="mdl-button mdl-js-button mdl-js-ripple-effect">Plus d'info</a>
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
	<div class="mdl-cell mdl-cell--12-col">
		<p>{{ empty_content }}</p>
	</div>
	{% endif %}
</div>
{% endblock %}

templates/markdownx/widget.html
<script type="text/javascript">
	django.jQuery( document ).ready(function() {
		django.jQuery('#editor_control').click(function() {
			if( django.jQuery('#editor_markdown').css('display') == 'none' ) {
				django.jQuery('#editor_markdown').css('display', 'block');
				django.jQuery('#editor_preview').css('display', 'none');
				django.jQuery('#editor_control').val('Preview');
			} else {
				django.jQuery('#editor_markdown').css('display', 'none');
				django.jQuery('#editor_preview').css('display', 'block');
				django.jQuery('#editor_control').val('Editor');
			}
		});
	});
</script>
<style>
#editor_markdown textarea {
	width: 99% !important;
}
#editor_preview .markdownx-preview {
	width: 99% !important;
}
</style>
<div class="markdownx row" style="width: calc(100% - 170px);">
		<input id="editor_control" type="button" value="Preview" />
    <div id="editor_markdown">
        {{ markdownx_editor }}
    </div>
    <div id="editor_preview" style="display: none;">
        <div class="markdownx-preview"></div>
    </div>
</div>

templates/menu.html
{% for link in links %}
	<a class="mdl-navigation__link{% if link.parent %} sub-category{% endif %}" href="{{ link.get_absolute_url }}">
		{% if link.icon %}
			<i class="fa fa-lg fa-{{ link.icon }}"></i>
		{% else %}
			<i class="fa fa-angle-right"></i>
		{% endif %}
		{{ link.name }}
	</a>
{% endfor %}